# Generated by Django 2.2 on 2019-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190428_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='data',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
